version: "3.7"
services:
    pyvhr-dev:
        build: ./
        image: pyvhr-img
        container_name: pyvhr-dev
        ports:
            - "8888:8888"
        volumes:
            - .:/app
            - C:/video/:/app/video
